default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: referral_invitation_development

test:
  <<: *default
  database: referral_invitation_test

production:
  <<: *default
  database: referral_invitation_production
  username: referral_invitation
  password: <%= ENV["REFERRAL_INVITATION_DATABASE_PASSWORD"] %>
